version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/upload_photo
    environment:
      - DEBUG=True
    image: upload/upload
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data__/db_upload:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db1
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=password123
